metastore:
    driverClassName: org.apache.phoenix.jdbc.PhoenixDriver
    id:
    password:
    url: #################################
    initPoolSize: 30
    maxPoolSize: 150
    minPoolSize: 10

auth:
    api:
        id: #################################
        password: #################################

redis:
    host: #################################
    password: #################################