inkconfig:
    filepath: /inkconfig.dev.properties

phoenix:
    driverClassName: org.apache.phoenix.jdbc.PhoenixDriver
    url: #################################
    initPoolSize: 1
    maxPoolSize: 10
    minPoolSize: 1

auth:
    api:
        id: #################################
        password: #################################

daemon_id:
    name: SA

multi_tenants:
    -  name: DA
       url: http://1.1.1.1/sql/run
